//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeWebApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class AdminUser
    {
        //[Required(ErrorMessage ="ID not empty ...")]
        [Display (Name ="Mã User")]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotDeclareVisibleInstanceFields")]
        public int ID { get; set; }

        //[Required(ErrorMessage = "Name not empty ...")] //[StringLength (50, Minimum Length =5)] [Display (Name = "Tên User")]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotDeclareVisibleInstanceFields")]
        public string NameUser { get; set; }

        [DisplayName("Vi tri")]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotDeclareVisibleInstanceFields")]
        public string RoleUser { get; set; }

        [DisplayName("Nhập Mật khẩu")]
        [Required(ErrorMessage = "Pass not empty ...")]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotDeclareVisibleInstanceFields")]
        [DataType(DataType.Password)]
        public string PasswordUser { get; set; }

        [NotMapped]
        [Compare("PasswordUser")]
        [DisplayName("Nhập lại mật khẩu")]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotDeclareVisibleInstanceFields")]
        public string ConfirmPass { get; set; }

        [NotMapped]
        [DisplayName("Lỗi đăng nhập")]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotDeclareVisibleInstanceFields")]
        public string ErrorLogin { get; set; }
    }
}
